### ISSUE TITLE
Trying to assign value of type 'Spatial' to a variable of type 'MeshInstance'

### ISSUE THREAD

**Issue by dirk-de-bugger** [hman278/Godot-Runner-Game#1]
Godot 3.2 has a problem with [scripts/level.gd line 112](https://github.com/hman278/Godot-Runner-Game/blob/0d79909c5c9e50f12b2ff5e6b75677253d0d49d6/scripts/level.gd#L112).

Changing it to
var rock_inst: **Spatial** = rock.instance()
appears to work.

**Comment by hman278** [comment]
Glad you found a fix!

**Comment by ghost** [comment]
@hman278 Why don't you push this change? It's good.

**Comment by hman278** [comment]
Oh I totally forgot about that. Will do

**Comment by infosisio** [comment]
@hman278 Awesome, I wanted to ask you, how do you achieve that slope as the player is running? I also don't see the ground being loaded somewhere, how does that happen? Thanks.
